### ISSUE TITLE
🧐

### ISSUE THREAD

**Issue by mrdbourke** [madewithbio/madewithbio.github.io#1]
> Hi Andrej :) I haven't publicized any of this yet so I'm sure this message will only find you. 

Reading through madewithml.com and stumbled upon this repo somehow.

Hope you're well :)

**Comment by GokuMohandas** [comment]
Hey @mrdbourke, sorry I didn't have notifications turned on for this yet! Nice to see you here and hope you're doing well too :) I've been meaning to catch up with you for a long time so I'm sending you a message on Twitter to get something on the calendar. Happy new year!
